version: '3.8'

services:
  # Selenium Hub
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/ui"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Chrome Node
  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
    scale: 2

  # WebdriverIO Test Runner
  webdriverio:
    build: .
    container_name: webdriverio-tests
    depends_on:
      - selenium-hub
      - chrome
    volumes:
      - ./test-reports:/app/test-reports
      - ./coverage:/app/coverage
      - ./allure-results:/app/allure-results
    environment:
      - CI=true
      - SELENIUM_HUB_URL=http://selenium-hub:4444
    command: ["npm", "run", "test:ci"]

  # Report Server (optional)
  report-server:
    build: .
    container_name: webdriverio-reports
    ports:
      - "3000:3000"
    volumes:
      - ./test-reports:/app/test-reports
    command: ["npx", "http-server", "test-reports", "-p", "3000"]
    depends_on:
      - webdriverio

networks:
  default:
    name: webdriverio-network