name: Continuous Integration

on:
  push:
    branches: [ main, ManHou, feature/* ]
  pull_request:
    branches: [ main, ManHou ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps (npm ci)
        run: npm ci

      - name: Build (automation)
        run: npm run build

      - name: Test (automation)
        run: npm run test
        # If your test script exits non-zero on failures, artifacts will still upload.
        # If you prefer the job to *not* fail the PR, add: continue-on-error: true

      - name: Upload build & test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.run_id }}
          if-no-files-found: ignore
          retention-days: 14
          path: |
            build-reports/**
            test-reports/**
            coverage/**
            dist/**

      # --- Optional: build and smoke-run your Docker image ---
      - name: Build Docker image
        working-directory: ./automation
        run: |
          docker build -t webdriverio:ci-${{ github.sha }} .

      - name: Smoke run container
        working-directory: ./automation
        run: |
          docker run --name wdio-ci -d webdriverio:ci-${{ github.sha }}
          sleep 5
          docker logs wdio-ci || true
          docker rm -f wdio-ci
