# .github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches: [ main, ManHou, feature/* ]
  pull_request:
    branches: [ main, ManHou ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  # Build and Test Automation
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run Build Automation
        working-directory: ./automation
        run: |
          echo "Running build automation..."
          node build-automation.js
          echo "Build completed"
      
      - name: Run Test Automation
        working-directory: ./automation
        run: |
          echo "Running test automation..."
          node test-automation.js || true
          echo "Tests completed"
      
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: automation-reports
          path: |
            automation/build-reports/
            automation/test-reports/

  # Docker Build
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        working-directory: ./automation
        run: |
          docker build -t webdriverio:ci-${{ github.sha }} .
          echo "Docker image built successfully"
      
      - name: Test Docker Container
        working-directory: ./automation
        run: |
          docker run -d --name test-container webdriverio:ci-${{ github.sha }}
          sleep 5
          docker logs test-container
          docker stop test-container
          docker rm test-container